name: "WOOWTECH HA Core 1"
description: "WOOWTECH-branded Home Assistant Core instance 1 with custom frontend"
version: "1.0.1"
slug: "woow_ha_core_1"
init: false
arch:
  - aarch64
  - amd64
ports:
  8123/tcp: 8124
map:
  - "config:rw"
